### ISSUE TITLE
Clean install config issues

### ISSUE THREAD

**Issue by dalager** [BuriedStPatrick/pwsh#3] opened 2022-03-27 17:16 UTC
Installing on a clean windows 11 installation is not working.
- install works ok
But when restarting shell there is no files in the appdata folder where the script is looking.

**Comment by BuriedStPatrick** [comment] 2022-04-01 20:57
Can reproduce! I think I fumbled some destination paths due to some colliding ideas about how the configs should be parsed.

Taking a look :)

**Comment by BuriedStPatrick** [comment] 2022-04-01 21:07
For the time being, workaround is installing the default config file:

1. Run `patch.ps1` in repo
2. Select `(3) Install default config`
3. Reload your PowerShell session

**Comment by BuriedStPatrick** [comment] 2022-04-02 01:51
@dalager Should be fixed in `3-clean-install-issues` :)

**Comment by BuriedStPatrick** [comment] 2022-04-04 12:19
@dalager I'm going ahead with the PR merge. You can re-open if the problem persists.

**Closed as completed** 2022-04-04 12:20 UTC
Labels: bug
